### ISSUE TITLE
How to use with other plugin ?

### ISSUE THREAD

**Issue by lriaudel** [moewe-io/osm-tiles-proxy#5]
Hi,

I want to use your plugin for put on cache my map of my plugin.
How can I get the local url ?
A function, a variable ?
Thanks

**Comment by scrobbleme** [comment]
Hello Iriaudel,

You will find the URLs in the plugins overview.
Is this, what you wanted?

![image](https://user-images.githubusercontent.com/504835/84771365-96251c80-afd9-11ea-9b52-01c21e23cde0.png)

**Comment by lriaudel** [comment]
No, If I used your plugin in an other plugin, I don't use an URL in plain text, I used a fonction or a variable.
It is not usable in this state.

**Comment by scrobbleme** [comment]
Okay, do you have some example code on how you would like to use it?

The URL to the cache files is basically: `content_url( '/cache/osm-tiles/{s}/{z}/{x}/{y}.png' )`

**Comment by lriaudel** [comment]
For example:

**Functions**
```
get_osm_tiles_proxy_url();
get_osm_tiles_proxy_url_rest_api();
get_osm_tiles_proxy_leaflet_js();
get_osm_tiles_proxy_leaflet_css();
```

**Or Constant**
```
define('OSM_TILES_PROXY_URL', 'http...{y}.png');
define('OSM_TILES_PROXY_URL_REST_API', 'http...{y}.png');
define('OSM_TILES_PROXY_LEAFLET_JS', 'http...leaflet.js');
define('OSM_TILES_PROXY_LEAFLET_CSS', 'http...leaflet.css');
```

**Comment by scrobbleme** [comment]
Ah good point, this makes sense.
I will try to add filters for this, so it eventually will look like:

`$proxy_url = apply_filter('get_osm_tiles_proxy_url', false);`

**Comment by scrobbleme** [comment]
@lriaudel 
I've released a new version, which contains filters. Please have a look at the readme.

Sorry for not replying to your questions on wordpress.org. I never got a notification for them, else I would ha ve answered.

**Comment by lriaudel** [comment]
Thanks, I integrate this in our plugins.

**Comment by scrobbleme** [comment]
@lriaudel I've added your plugin to list of compatible plugins.

**Comment by lriaudel** [comment]
LOL, I didn't even have time to tell you it was good ;-)

-> https://wordpress.org/plugins/cpt-to-map-store/
